### ISSUE TITLE
new workflow时候报错，workflow的值是必填的

### ISSUE THREAD

**Issue by kxu1988** [rails-engine/workflow_core#3]
创建新的workflow的时候报错：NOT NULL constraint failed: forms.name，
代码这里创建form的时候，没有name，但是数据库里name是必填的
   ```
 def auto_create_form!
      create_form! type: "Form"
    end
```

**Comment by jasl** [comment]
可能是跟我前阵子升级 FormCore 有关，我来修一下，如果新版不复现的话，你可以简单修改

```ruby
def auto_create_form!
  create_form! type: "Form", name: SecureRandom.hex(4)
end
```

**Comment by jasl** [comment]
我看了代码，现在的版本是没问题的，你可以用我上一个回复说的方法修改一下代码么？

这个项目目前在我的一个商业项目里使用，交付后我会根据这过程的经验对这个项目做一些更新

**Comment by kxu1988** [comment]
好的，多谢

**Comment by jasl** [comment]
发现是我的问题，已修复。

另，我对演示项目做了大翻新，支持了审批人，加了一个演示用的流程
